export const ADD_BOOK_COMPILATION_REQUEST = "ADD_BOOK_COMPILATION_REQUEST"
export const ADD_BOOK_COMPILATION_REQUEST_SUCCESS = "ADD_BOOK_COMPILATION_REQUEST_SUCCESS"
export const ADD_BOOK_COMPILATION_REQUEST_ERROR = "ADD_BOOK_COMPILATION_REQUEST_ERROR"

export const ADD_BOOK_COMPILATION_TRADE_REQUEST = "ADD_BOOK_COMPILATION_TRADE_REQUEST"
export const ADD_BOOK_COMPILATION_TRADE_REQUEST_SUCCESS = "ADD_BOOK_COMPILATION_TRADE_REQUEST_SUCCESS"
export const ADD_BOOK_COMPILATION_TRADE_REQUEST_ERROR = "ADD_BOOK_COMPILATION_TRADE_REQUEST_ERROR"


export const GET_BOOK_COMPILATION_REQUEST = "GET_BOOK_COMPILATION_REQUEST"
export const GET_BOOK_COMPILATION_REQUEST_SUCCESS = "GET_BOOK_COMPILATION_REQUEST_SUCCESS"
export const GET_BOOK_COMPILATION_REQUEST_ERROR = "GET_BOOK_COMPILATION_REQUEST_ERROR"


export const SELECTED_BOOK = "SELECTED_BOOK"

export const ADD_EXAMPLES_BOOKS_REQUEST = "ADD_EXAMPLES_BOOKS_REQUEST"
export const ADD_EXAMPLES_BOOKS_REQUEST_SUCCESS = "ADD_EXAMPLES_BOOKS_REQUEST_SUCCESS"
export const ADD_EXAMPLES_BOOKS_REQUEST_ERROR = "ADD_EXAMPLES_BOOKS_REQUEST_ERROR"


export const DELETE_BOOK_COMPILATION_REQUEST = "DELETE_BOOK_COMPILATION_REQUEST"
export const DELETE_BOOK_COMPILATION_REQUEST_SUCCESS = "DELETE_BOOK_COMPILATION_REQUEST_SUCCESS"
export const DELETE_BOOK_COMPILATION_REQUEST_ERROR = "DELETE_BOOK_COMPILATION_REQUEST_ERROR"



export const GET_BOOK_STATUS_REQUEST = "GET_BOOK_STATUS_REQUEST"
export const GET_BOOK_STATUS_REQUEST_SUCCESS = "GET_BOOK_STATUS_REQUEST_SUCCESS"
export const GET_BOOK_STATUS_ISSUE_REQUEST_SUCCESS = "GET_BOOK_STATUS_ISSUE_REQUEST_SUCCESS"
export const GET_BOOK_STATUS_REQUEST_ERROR = "GET_BOOK_STATUS_REQUEST_ERROR"


export const ADD_ORDER_REQUEST = "ADD_ORDER_REQUEST"
export const ADD_ORDER_REQUEST_SUCCESS = "ADD_ORDER_REQUEST_SUCCESS"
export const ADD_ORDER_REQUEST_ERROR = "ADD_ORDER_REQUEST_ERROR"


export const CLOSE_ORDER_REQUEST = "CLOSE_ORDER_REQUEST"
export const CLOSE_ORDER_REQUEST_SUCCESS = "CLOSE_ORDER_REQUEST_SUCCESS"
export const CLOSE_ORDER_REQUEST_ERROR = "CLOSE_ORDER_REQUEST_ERROR"
